In [1]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Helen', 'Ian', 'Julia'],
    'Age': [25, 30, 35, 40, 28, 33, 27, 45, 31, 38],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'Finance', 'Marketing', 'IT', 'Marketing', 'Finance'],
    'Salary': [5000, 7000, 8000, 9000, 5200, 7800, 6100, 9500, 6200, 8800],
    'Experience': [2, 5, 8, 10, 3, 7, 4, 12, 6, 9],
    'Gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'F']
}

df = pd.DataFrame(data)
df

      Name  Age Department  Salary  Experience Gender
0    Alice   25         HR    5000           2      F
1      Bob   30         IT    7000           5      M
2  Charlie   35    Finance    8000           8      M
3    David   40         IT    9000          10      M
4      Eva   28         HR    5200           3      F
5    Frank   33    Finance    7800           7      M
6    Grace   27  Marketing    6100           4      F
7    Helen   45         IT    9500          12      F
8      Ian   31  Marketing    6200           6      M
9    Julia   38    Finance    8800           9      F

In [2]:
df.head(5)

      Name  Age Department  Salary  Experience Gender
0    Alice   25         HR    5000           2      F
1      Bob   30         IT    7000           5      M
2  Charlie   35    Finance    8000           8      M
3    David   40         IT    9000          10      M
4      Eva   28         HR    5200           3      F

In [10]:
df.loc[(df['Department'] == 'IT') & (df['Salary'] > 8000)]

    Name  Age Department  Salary  Experience Gender
3  David   40         IT    9000          10      M
7  Helen   45         IT    9500          12      F

In [16]:
df.groupby('Department').size()

Department
Finance      3
HR           2
IT           3
Marketing    2
dtype: int64

In [17]:
df.groupby('Department').agg({'Salary': 'mean', 'Age': 'mean'})

            Salary        Age
Department
Finance     8200.0  35.333333
HR          5100.0  26.500000
IT          8500.0  38.333333
Marketing   6150.0  29.000000

In [18]:
def category(row):
    if row['Experience'] >= 8:
        return 'Senior'
    elif row['Experience'] >= 4:
        return 'Mid'
    else:
        return 'Junior'

df['Seniority'] = df.apply(category, axis=1)

In [19]:
df.head()

      Name  Age Department  Salary  Experience Gender Seniority
0    Alice   25         HR    5000           2      F    Junior
1      Bob   30         IT    7000           5      M       Mid
2  Charlie   35    Finance    8000           8      M    Senior
3    David   40         IT    9000          10      M    Senior
4      Eva   28         HR    5200           3      F    Junior

In [30]:
df.nlargest(3, 'Salary')[['Name', 'Department', 'Salary']]

    Name Department  Salary
7  Helen         IT    9500
3  David         IT    9000
9  Julia    Finance    8800

In [23]:
df.sort_values(['Salary'], ascending=False)

      Name  Age Department  Salary  Experience Gender Seniority
7    Helen   45         IT    9500          12      F    Senior
3    David   40         IT    9000          10      M    Senior
9    Julia   38    Finance    8800           9      F    Senior
2  Charlie   35    Finance    8000           8      M    Senior
5    Frank   33    Finance    7800           7      M       Mid
1      Bob   30         IT    7000           5      M       Mid
8      Ian   31  Marketing    6200           6      M       Mid
6    Grace   27  Marketing    6100           4      F       Mid
4      Eva   28         HR    5200           3      F    Junior
0    Alice   25         HR    5000           2      F    Junior

In [34]:
avg_salary = df.groupby('Gender')['Salary'].mean()
diff = avg_salary['M'] - avg_salary['F']
print("男女平均薪资差异为：", diff)

男女平均薪资差异为： 680.0

In [35]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Helen', 'Ian', 'Julia'],
    'Age': [25, 30, 35, 28, 42, 50, 33, 29, 41, 26],
    'Department': ['HR', 'IT', 'IT', 'Finance', 'HR', 'Finance', 'IT', 'Marketing', 'Marketing', 'Finance'],
    'Salary': [5000, 8000, 9500, 7000, 5400, 12000, 8800, 6000, 6500, 11000],
    'Gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'F']
}

df = pd.DataFrame(data)
df

      Name  Age Department  Salary Gender
0    Alice   25         HR    5000      F
1      Bob   30         IT    8000      M
2  Charlie   35         IT    9500      M
3    David   28    Finance    7000      M
4      Eva   42         HR    5400      F
5    Frank   50    Finance   12000      M
6    Grace   33         IT    8800      F
7    Helen   29  Marketing    6000      F
8      Ian   41  Marketing    6500      M
9    Julia   26    Finance   11000      F

In [36]:
df.head(5)

      Name  Age Department  Salary Gender
0    Alice   25         HR    5000      F
1      Bob   30         IT    8000      M
2  Charlie   35         IT    9500      M
3    David   28    Finance    7000      M
4      Eva   42         HR    5400      F

In [38]:
df.isna()

    Name    Age  Department  Salary  Gender
0  False  False       False   False   False
1  False  False       False   False   False
2  False  False       False   False   False
3  False  False       False   False   False
4  False  False       False   False   False
5  False  False       False   False   False
6  False  False       False   False   False
7  False  False       False   False   False
8  False  False       False   False   False
9  False  False       False   False   False

In [39]:
df.loc[df['Salary'] > 8000]

      Name  Age Department  Salary Gender
2  Charlie   35         IT    9500      M
5    Frank   50    Finance   12000      M
6    Grace   33         IT    8800      F
9    Julia   26    Finance   11000      F

In [41]:
df.loc[(df['Department'] == 'IT') & (df['Age'] < 35)]

    Name  Age Department  Salary Gender
1    Bob   30         IT    8000      M
6  Grace   33         IT    8800      F

In [44]:
df.sort_values(['Salary'], ascending=False)[['Name', 'Salary']]

      Name  Salary
5    Frank   12000
9    Julia   11000
2  Charlie    9500
6    Grace    8800
1      Bob    8000
3    David    7000
8      Ian    6500
7    Helen    6000
4      Eva    5400
0    Alice    5000

In [46]:
def level(row):
    if row['Salary'] >= 9000:
        return 'High'
    else:
        return 'Low'

df['Salary_Level'] = df.apply(level, axis=1)

In [47]:
df

      Name  Age Department  Salary Gender Salary_Level
0    Alice   25         HR    5000      F          Low
1      Bob   30         IT    8000      M          Low
2  Charlie   35         IT    9500      M         High
3    David   28    Finance    7000      M          Low
4      Eva   42         HR    5400      F          Low
5    Frank   50    Finance   12000      M         High
6    Grace   33         IT    8800      F          Low
7    Helen   29  Marketing    6000      F          Low
8      Ian   41  Marketing    6500      M          Low
9    Julia   26    Finance   11000      F         High

In [48]:
df.groupby('Department')['Salary'].mean()

Department
Finance      10000.000000
HR            5200.000000
IT            8766.666667
Marketing     6250.000000
Name: Salary, dtype: float64

In [51]:
df.groupby('Gender').size()

Gender
F    5
M    5
dtype: int64

In [54]:
df.sort_values(['Salary'], ascending=False).head(1)

    Name  Age Department  Salary Gender Salary_Level
5  Frank   50    Finance   12000      M         High

In [59]:
idx = df.groupby('Department')['Salary'].idxmax()
df.loc[idx, ['Department', 'Name', 'Salary']]

  Department     Name  Salary
5    Finance    Frank   12000
4         HR      Eva    5400
2         IT  Charlie    9500
8  Marketing      Ian    6500

In [60]:
import pandas as pd

# 主表：员工
df = pd.DataFrame({
    'Name': ['Alice','Bob','Charlie','David','Eva','Frank','Grace','Helen','Ian','Julia'],
    'Age':  [25, 30, 35, 28, 42, 50, 33, 29, 41, 26],
    'Department': ['HR','IT','IT','Finance','HR','Finance','IT','Marketing','Marketing','Finance'],
    'Salary': [5000, 8000, 9500, 7000, 5400, 12000, 8800, 6000, 6500, 11000],
    'Gender': ['F','M','M','M','F','M','F','F','M','F'],
    'HireDate': [
        '2020-03-01','2019-07-15','2018-01-20','2021-06-01','2017-09-30',
        '2015-12-12','2019-04-18','2022-02-10','2016-10-21','2018-07-07'
    ],
    'Email': [
        'alice@corp.com','bob@corp.com','charlie@corp.com','david@corp.com','eva@corp.com',
        'frank@corp.com','grace@corp.com','helen@corp.com','ian@corp.com','julia@corp.com'
    ],
    'City': ['SF','NY','NY','SF','SF','LA','NY','LA','LA','SF'],
    # 故意留一些缺失或0，给你练清洗
    'Bonus': [500, 0, 1200, None, 200, 300, None, 0, 150, 1000],
    # 多值字段，待练习 split / explode
    'Skills': [
        'Excel,HR','Python,SQL','Python,ML','Excel,Finance','Excel,HR',
        'Finance,SQL','Python,Visualization','Marketing,Excel','Marketing,SQL','Finance,Python'
    ]
})

# 辅助表1：部门信息
dept_info = pd.DataFrame({
    'Department': ['HR','IT','Finance','Marketing'],
    'DeptHead':   ['Nina','Oscar','Paul','Queen'],
    'Location':   ['Building A','Building B','Building A','Building C']
})

# 辅助表2：年度绩效评分（不含所有人，便于练习连接缺失）
perf = pd.DataFrame({
    'Name': ['Alice','Bob','Charlie','Eva','Frank','Grace','Ian'],
    'Year': [2024, 2024, 2024, 2024, 2024, 2024, 2024],
    'Rating': [4.5, 4.2, 4.8, 3.9, 4.7, 4.3, 4.0]
})

# 辅助表3：工时记录（用于时间序列、分组、聚合）
timesheet = pd.DataFrame({
    'Name': ['Alice','Alice','Bob','Charlie','Charlie','Grace','Helen','Ian','Ian','Julia','Frank','David'],
    'Date': ['2024-07-01','2024-07-08','2024-07-03','2024-07-02','2024-07-09','2024-07-05','2024-07-01',
             '2024-07-04','2024-07-11','2024-07-06','2024-07-07','2024-07-03'],
    'Hours': [8, 7, 9, 6, 8, 7, 5, 9, 8, 6, 10, 7]
})

In [78]:
df['HireDate'] = pd.to_datetime(df['HireDate'])
today = pd.Timestamp('today').normalize()
today

Timestamp('2025-11-05 00:00:00')

In [80]:
df['Tenure_Y'] = ((today - df['HireDate']).dt.days/365.25).round(1)
df.head()

,Name,Age,Department,Salary,Gender,HireDate,Email,City,Bonus,Skills,Tenure_Y
0,Alice,25,HR,5000,F,2020-03-01,alice@corp.com,SF,500.0,"Excel,HR",5.7
1,Bob,30,IT,8000,M,2019-07-15,bob@corp.com,NY,0.0,"Python,SQL",6.3
2,Charlie,35,IT,9500,M,2018-01-20,charlie@corp.com,NY,1200.0,"Python,ML",7.8
3,David,28,Finance,7000,M,2021-06-01,david@corp.com,SF,NaN,"Excel,Finance",4.4
4,Eva,42,HR,5400,F,2017-09-30,eva@corp.com,SF,200.0,"Excel,HR",8.1

In [84]:
df['Bonus'] = pd.to_numeric(df['Bonus']).fillna(0)
df

,Name,Age,Department,Salary,Gender,HireDate,Email,City,Bonus,Skills,Tenure_Y
0,Alice,25,HR,5000,F,2020-03-01,alice@corp.com,SF,500.0,"Excel,HR",5.7
1,Bob,30,IT,8000,M,2019-07-15,bob@corp.com,NY,0.0,"Python,SQL",6.3
2,Charlie,35,IT,9500,M,2018-01-20,charlie@corp.com,NY,1200.0,"Python,ML",7.8
3,David,28,Finance,7000,M,2021-06-01,david@corp.com,SF,0.0,"Excel,Finance",4.4
4,Eva,42,HR,5400,F,2017-09-30,eva@corp.com,SF,200.0,"Excel,HR",8.1
5,Frank,50,Finance,12000,M,2015-12-12,frank@corp.com,LA,300.0,"Finance,SQL",9.9
6,Grace,33,IT,8800,F,2019-04-18,grace@corp.com,NY,0.0,"Python,Visualization",6.6
7,Helen,29,Marketing,6000,F,2022-02-10,helen@corp.com,LA,0.0,"Marketing,Excel",3.7
8,Ian,41,Marketing,6500,M,2016-10-21,ian@corp.com,LA,150.0,"Marketing,SQL",9.0
9,Julia,26,Finance,11000,F,2018-07-07,julia@corp.com,SF,1000.0,"Finance,Python",7.3

In [85]:
df['TotalComp'] = df['Salary'] + df['Bonus']

In [86]:
df

,Name,Age,Department,Salary,Gender,HireDate,Email,City,Bonus,Skills,Tenure_Y,TotalComp
0,Alice,25,HR,5000,F,2020-03-01,alice@corp.com,SF,500.0,"Excel,HR",5.7,5500.0
1,Bob,30,IT,8000,M,2019-07-15,bob@corp.com,NY,0.0,"Python,SQL",6.3,8000.0
2,Charlie,35,IT,9500,M,2018-01-20,charlie@corp.com,NY,1200.0,"Python,ML",7.8,10700.0
3,David,28,Finance,7000,M,2021-06-01,david@corp.com,SF,0.0,"Excel,Finance",4.4,7000.0
4,Eva,42,HR,5400,F,2017-09-30,eva@corp.com,SF,200.0,"Excel,HR",8.1,5600.0
5,Frank,50,Finance,12000,M,2015-12-12,frank@corp.com,LA,300.0,"Finance,SQL",9.9,12300.0
6,Grace,33,IT,8800,F,2019-04-18,grace@corp.com,NY,0.0,"Python,Visualization",6.6,8800.0
7,Helen,29,Marketing,6000,F,2022-02-10,helen@corp.com,LA,0.0,"Marketing,Excel",3.7,6000.0
8,Ian,41,Marketing,6500,M,2016-10-21,ian@corp.com,LA,150.0,"Marketing,SQL",9.0,6650.0
9,Julia,26,Finance,11000,F,2018-07-07,julia@corp.com,SF,1000.0,"Finance,Python",7.3,12000.0

In [87]:
def level(row):
    if row['Salary'] >= 9000:
        return 'High'
    else:
        return 'Low'
df['SalaryLevel'] = df.apply(level, axis=1)

In [89]:
df.groupby('SalaryLevel').size()

SalaryLevel
High    3
Low     7
dtype: int64

In [97]:
df['DeptRank'] = df.groupby('Department')['Salary'].rank(method='first', ascending=False)

In [99]:
df[df['DeptRank'] <=2]

,Name,Age,Department,Salary,Gender,HireDate,Email,City,Bonus,Skills,Tenure_Y,TotalComp,SalaryLevel,DeptRank
0,Alice,25,HR,5000,F,2020-03-01,alice@corp.com,SF,500.0,"Excel,HR",5.7,5500.0,Low,2.0
2,Charlie,35,IT,9500,M,2018-01-20,charlie@corp.com,NY,1200.0,"Python,ML",7.8,10700.0,High,1.0
4,Eva,42,HR,5400,F,2017-09-30,eva@corp.com,SF,200.0,"Excel,HR",8.1,5600.0,Low,1.0
5,Frank,50,Finance,12000,M,2015-12-12,frank@corp.com,LA,300.0,"Finance,SQL",9.9,12300.0,High,1.0
6,Grace,33,IT,8800,F,2019-04-18,grace@corp.com,NY,0.0,"Python,Visualization",6.6,8800.0,Low,2.0
7,Helen,29,Marketing,6000,F,2022-02-10,helen@corp.com,LA,0.0,"Marketing,Excel",3.7,6000.0,Low,2.0
8,Ian,41,Marketing,6500,M,2016-10-21,ian@corp.com,LA,150.0,"Marketing,SQL",9.0,6650.0,Low,1.0
9,Julia,26,Finance,11000,F,2018-07-07,julia@corp.com,SF,1000.0,"Finance,Python",7.3,12000.0,High,2.0

In [100]:
q75 = df.groupby('Department')['Salary'].transform(lambda x: x.quantile(0.75))
high_earn = df[df['Salary'] > q75]
high_earn

,Name,Age,Department,Salary,Gender,HireDate,Email,City,Bonus,Skills,Tenure_Y,TotalComp,SalaryLevel,DeptRank
2,Charlie,35,IT,9500,M,2018-01-20,charlie@corp.com,NY,1200.0,"Python,ML",7.8,10700.0,High,1.0
4,Eva,42,HR,5400,F,2017-09-30,eva@corp.com,SF,200.0,"Excel,HR",8.1,5600.0,Low,1.0
5,Frank,50,Finance,12000,M,2015-12-12,frank@corp.com,LA,300.0,"Finance,SQL",9.9,12300.0,High,1.0
8,Ian,41,Marketing,6500,M,2016-10-21,ian@corp.com,LA,150.0,"Marketing,SQL",9.0,6650.0,Low,1.0

In [103]:
pivot = df.pivot_table(columns='Gender', index='Department', values='Salary', aggfunc='mean')
pivot

Gender            F       M
Department
Finance     11000.0  9500.0
HR           5200.0     NaN
IT           8800.0  8750.0
Marketing    6000.0  6500.0

In [104]:
import pandas as pd

data = {
    'Name': ['Alice','Bob','Charlie','David','Eva','Frank','Grace','Helen','Ian','Jack'],
    'Age':  [25, 32, 37, 29, 41, 28, 35, 30, 26, 45],
    'Gender': ['F','M','M','M','F','M','F','F','M','M'],
    'Department': ['HR','IT','IT','Finance','Finance','HR','IT','HR','Finance','IT'],
    'Salary': [4800, 7200, 6900, 8500, 9000, 5200, 6400, 5800, 7700, 8100],
    'YearsAtCompany': [1, 5, 3, 7, 10, 2, 4, 6, 8, 9]
}

df = pd.DataFrame(data)
df

      Name  Age Gender Department  Salary  YearsAtCompany
0    Alice   25      F         HR    4800               1
1      Bob   32      M         IT    7200               5
2  Charlie   37      M         IT    6900               3
3    David   29      M    Finance    8500               7
4      Eva   41      F    Finance    9000              10
5    Frank   28      M         HR    5200               2
6    Grace   35      F         IT    6400               4
7    Helen   30      F         HR    5800               6
8      Ian   26      M    Finance    7700               8
9     Jack   45      M         IT    8100               9

In [105]:
df.head(5)

      Name  Age Gender Department  Salary  YearsAtCompany
0    Alice   25      F         HR    4800               1
1      Bob   32      M         IT    7200               5
2  Charlie   37      M         IT    6900               3
3    David   29      M    Finance    8500               7
4      Eva   41      F    Finance    9000              10

In [107]:
df.columns

Index(['Name', 'Age', 'Gender', 'Department', 'Salary', 'YearsAtCompany'], dtype='object')

In [118]:
len(df)

10

In [119]:
df.groupby('Department').size()

Department
Finance    3
HR         3
IT         4
dtype: int64

In [120]:
df.loc[df['Department'] == 'IT']

      Name  Age Gender Department  Salary  YearsAtCompany
1      Bob   32      M         IT    7200               5
2  Charlie   37      M         IT    6900               3
6    Grace   35      F         IT    6400               4
9     Jack   45      M         IT    8100               9

In [121]:
df.loc[df['Salary'] >= 7000]

    Name  Age Gender Department  Salary  YearsAtCompany
1    Bob   32      M         IT    7200               5
3  David   29      M    Finance    8500               7
4    Eva   41      F    Finance    9000              10
8    Ian   26      M    Finance    7700               8
9   Jack   45      M         IT    8100               9

In [122]:
df.loc[(df['Department'] == 'Finance') & (df['Salary'] > 8000)]

    Name  Age Gender Department  Salary  YearsAtCompany
3  David   29      M    Finance    8500               7
4    Eva   41      F    Finance    9000              10

In [125]:
df.loc[df['Gender'] == 'F'][['Name', 'Salary', 'Gender']]

    Name  Salary Gender
0  Alice    4800      F
4    Eva    9000      F
6  Grace    6400      F
7  Helen    5800      F

In [126]:
df.sort_values('Salary', ascending=False)

      Name  Age Gender Department  Salary  YearsAtCompany
4      Eva   41      F    Finance    9000              10
3    David   29      M    Finance    8500               7
9     Jack   45      M         IT    8100               9
8      Ian   26      M    Finance    7700               8
1      Bob   32      M         IT    7200               5
2  Charlie   37      M         IT    6900               3
6    Grace   35      F         IT    6400               4
7    Helen   30      F         HR    5800               6
5    Frank   28      M         HR    5200               2
0    Alice   25      F         HR    4800               1

In [128]:
df.sort_values(by=['Department', 'Salary'], ascending=[True, False])

      Name  Age Gender Department  Salary  YearsAtCompany
4      Eva   41      F    Finance    9000              10
3    David   29      M    Finance    8500               7
8      Ian   26      M    Finance    7700               8
7    Helen   30      F         HR    5800               6
5    Frank   28      M         HR    5200               2
0    Alice   25      F         HR    4800               1
9     Jack   45      M         IT    8100               9
1      Bob   32      M         IT    7200               5
2  Charlie   37      M         IT    6900               3
6    Grace   35      F         IT    6400               4

In [131]:
df.groupby('Department').agg({'Salary': 'mean'})

                 Salary
Department
Finance     8400.000000
HR          5266.666667
IT          7150.000000

In [135]:
df.groupby('Gender').agg({'Name': 'count', 'Salary': 'mean'})

        Name       Salary
Gender
F          4  6500.000000
M          6  7266.666667

In [136]:
def level(row):
    if row['Salary'] >= 8000:
        return 'High'
    elif row['Salary'] >= 6000:
        return 'Medium'
    else:
        return 'Low'
df['SalaryLevel'] = df.apply(level, axis=1)

In [137]:
df

      Name  Age Gender Department  Salary  YearsAtCompany SalaryLevel
0    Alice   25      F         HR    4800               1         Low
1      Bob   32      M         IT    7200               5      Medium
2  Charlie   37      M         IT    6900               3      Medium
3    David   29      M    Finance    8500               7        High
4      Eva   41      F    Finance    9000              10        High
5    Frank   28      M         HR    5200               2         Low
6    Grace   35      F         IT    6400               4      Medium
7    Helen   30      F         HR    5800               6         Low
8      Ian   26      M    Finance    7700               8      Medium
9     Jack   45      M         IT    8100               9        High

In [141]:
idx = df.groupby('Department')['Salary'].idxmax()
df.loc[idx, ['Name', 'Salary']]

    Name  Salary
4    Eva    9000
7  Helen    5800
9   Jack    8100

In [142]:
df['dep_avg'] = df.groupby('Department')['Salary'].transform('mean')

In [144]:
df['DiffFromDeptAvg'] = df['dep_avg'] - df['Salary']

In [147]:
df.groupby('Department')['Age'].median()

Department
Finance    29.0
HR         28.0
IT         36.0
Name: Age, dtype: float64

In [148]:
df['DeptRank'] = df.groupby('Department')['Salary'].rank(ascending=False)

In [149]:
df

,Name,Age,Gender,Department,Salary,YearsAtCompany,SalaryLevel,dep_avg,DiffFromDeptAvg,DeptRank
0,Alice,25,F,HR,4800,1,Low,5266.666667,466.666667,3.0
1,Bob,32,M,IT,7200,5,Medium,7150.000000,-50.000000,2.0
2,Charlie,37,M,IT,6900,3,Medium,7150.000000,250.000000,3.0
3,David,29,M,Finance,8500,7,High,8400.000000,-100.000000,2.0
4,Eva,41,F,Finance,9000,10,High,8400.000000,-600.000000,1.0
5,Frank,28,M,HR,5200,2,Low,5266.666667,66.666667,2.0
6,Grace,35,F,IT,6400,4,Medium,7150.000000,750.000000,4.0
7,Helen,30,F,HR,5800,6,Low,5266.666667,-533.333333,1.0
8,Ian,26,M,Finance,7700,8,Medium,8400.000000,700.000000,3.0
9,Jack,45,M,IT,8100,9,High,7150.000000,-950.000000,1.0

In [150]:
df[df['DeptRank'] <= 2]

,Name,Age,Gender,Department,Salary,YearsAtCompany,SalaryLevel,dep_avg,DiffFromDeptAvg,DeptRank
1,Bob,32,M,IT,7200,5,Medium,7150.000000,-50.000000,2.0
3,David,29,M,Finance,8500,7,High,8400.000000,-100.000000,2.0
4,Eva,41,F,Finance,9000,10,High,8400.000000,-600.000000,1.0
5,Frank,28,M,HR,5200,2,Low,5266.666667,66.666667,2.0
7,Helen,30,F,HR,5800,6,Low,5266.666667,-533.333333,1.0
9,Jack,45,M,IT,8100,9,High,7150.000000,-950.000000,1.0

In [156]:
df.loc[(df['Age'] > 30) & (df['Salary'] > 6000) & (df['Salary'] < 12000),
    ['Name', 'Age', 'Department', 'Salary']
    ].sort_values('Salary', ascending=False)

      Name  Age Department  Salary
4      Eva   41    Finance    9000
9     Jack   45         IT    8100
1      Bob   32         IT    7200
2  Charlie   37         IT    6900
6    Grace   35         IT    6400

In [155]:
df['Name'].str.contains('A', 'a')

0     True
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: Name, dtype: bool

In [157]:
df['RankInDept'] = df.groupby('Department')['Salary'].rank(ascending=False)

In [162]:
df.del['RankInDept']

SyntaxError: invalid syntax (1712088184.py, line 1)

In [164]:
pivot = df.pivot_table(columns='Gender', index='Department', values='Salary', aggfunc='mean')
pivot

Gender           F       M
Department
Finance     9000.0  8100.0
HR          5300.0  5200.0
IT          6400.0  7400.0

In [165]:
df.groupby('Department').apply(lambda g: g.nlargest(2, 'Salary'))

/var/folders/_t/99rhfqy12md_q88dy260m5d80000gn/T/ipykernel_25690/1849732978.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('Department').apply(lambda g: g.nlargest(2, 'Salary'))

               Name  Age Gender Department  Salary  YearsAtCompany  \
Department
Finance    4    Eva   41      F    Finance    9000              10
           3  David   29      M    Finance    8500               7
HR         7  Helen   30      F         HR    5800               6
           5  Frank   28      M         HR    5200               2
IT         9   Jack   45      M         IT    8100               9
           1    Bob   32      M         IT    7200               5

             SalaryLevel      dep_avg  DiffFromDeptAvg  DeptRank  RankInDept
Department
Finance    4        High  8400.000000      -600.000000       1.0         1.0
           3        High  8400.000000      -100.000000       2.0         2.0
HR         7         Low  5266.666667      -533.333333       1.0         1.0
           5         Low  5266.666667        66.666667       2.0         2.0
IT         9        High  7150.000000      -950.000000       1.0         1.0
           1      Medium  7150.000000       -50.000000       2.0         2.0