In [1]:
import pandas as pd

In [58]:
import os
os.getcwd()

'/Users/mr.tian'

In [568]:
coffee = pd.read_csv('/Users/mr.tian/Desktop/coffee.csv')

In [66]:
results = pd.read_csv('/Users/mr.tian/Desktop/results.csv')

In [74]:
olympics_data = pd.read_excel('/Users/mr.tian/Desktop/olympics-data.xlsx', sheet_name = "results")

In [78]:
bios = pd.read_csv('/Users/mr.tian/Desktop/bios.csv')

In [107]:
coffee.sample(10, random_state=1)

          Day Coffee Type  Units Sold
3     Tuesday       Latte          20
7    Thursday       Latte          30
6    Thursday    Espresso          40
2     Tuesday    Espresso          30
10   Saturday    Espresso          45
4   Wednesday    Espresso          35
1      Monday       Latte          15
12     Sunday    Espresso          45
0      Monday    Espresso          25
13     Sunday       Latte          35

In [129]:
coffee.loc[0:3, ["Day", "Units Sold"]]

       Day  Units Sold
0   Monday          25
1   Monday          15
2  Tuesday          30
3  Tuesday          20

In [135]:
coffee.iloc[0:4, [0,2]]

       Day  Units Sold
0   Monday          25
1   Monday          15
2  Tuesday          30
3  Tuesday          20

In [193]:
coffee.index = coffee["Day"]

In [235]:
coffee.loc[0, "Units Sold"] = 25

In [237]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso        25.0
1     Monday       Latte        15.0
2    Tuesday    Espresso        30.0
3    Tuesday       Latte        20.0
4  Wednesday    Espresso        35.0

In [256]:
coffee.sort_values(["Units Sold", "Coffee Type"], ascending=False)

          Day Coffee Type  Units Sold
8      Friday    Espresso        45.0
10   Saturday    Espresso        45.0
12     Sunday    Espresso        45.0
6    Thursday    Espresso        40.0
9      Friday       Latte        35.0
11   Saturday       Latte        35.0
13     Sunday       Latte        35.0
4   Wednesday    Espresso        35.0
7    Thursday       Latte        30.0
2     Tuesday    Espresso        30.0
5   Wednesday       Latte        25.0
0      Monday    Espresso        25.0
3     Tuesday       Latte        20.0
1      Monday       Latte        15.0
14        NaN         NaN        10.0

In [258]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [286]:
bios[bios["born_country"].isin(['USA', 'FRA', 'GBR']) & (bios['name'].str.startswith("Austin"))]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
18727,18855,Austin Savage,1940-02-15,St Asaph,Wales,GBR,Great Britain,174.0,73.0,NaN
47023,47373,Austin Rawlinson,1902-11-07,Garston,England,GBR,Great Britain,NaN,NaN,2000-11-25
50934,51293,Austin Clapp,1910-11-08,Farmington,New Hampshire,USA,United States,NaN,NaN,1971-12-22
78189,78780,Austin Menaul,1888-03-26,Albuquerque,New Mexico,USA,United States,178.0,71.0,1975-10-17
116512,117906,Austin Sperry,1978-05-11,Oakland,California,USA,United States,185.0,102.0,NaN
133390,136329,Austin Hack,1992-05-17,Springfield,Massachusetts,USA,United States,203.0,100.0,NaN
143824,147480,Austin Krajicek,1990-06-16,Tampa,Florida,USA,United States,188.0,NaN,NaN

In [294]:
bios.query('born_country == "USA" and born_city == "Seattle"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
11030,11088,David Halpern,1955-08-18,Seattle,Washington,USA,United States,178.0,79.0,NaN
12800,12870,Todd Trewin,1958-04-20,Seattle,Washington,USA,United States,180.0,75.0,NaN
15476,15583,Scott McKinley,1968-10-15,Seattle,Washington,USA,United States,183.0,75.0,NaN
29079,29293,Joyce Tanac,1950-09-27,Seattle,Washington,USA,United States,156.0,49.0,NaN
31135,31371,Bill Kuhlemeier,1908-01-14,Seattle,Washington,USA,United States,NaN,NaN,2001-07-08
...,...,...,...,...,...,...,...,...,...,...
133392,136331,Hans Struzyna,1989-03-31,Seattle,Washington,USA,United States,188.0,91.0,NaN
135448,138662,Maude Davis Crossland,2003-03-19,Seattle,Washington,USA,Colombia,NaN,NaN,NaN
136993,140229,Jenell Berhorst,2003-12-13,Seattle,Washington,USA,United States,NaN,NaN,NaN
143507,147159,Nevin Harrison,2002-06-02,Seattle,Washington,USA,United States,175.0,73.0,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN

In [346]:
coffee_new['Price'] = 4.99

In [350]:
import numpy as np
coffee_new['new_price'] = np.where(coffee_new['Coffee Type'] == 'Espresso', 3.99, 5.99)

In [340]:
coffee_new = coffee.copy()

In [358]:
coffee_new

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       3.99
1      Monday       Latte          15       5.99
2     Tuesday    Espresso          30       3.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       3.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       3.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       3.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       3.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       3.99
13     Sunday       Latte          35       5.99

In [572]:
coffee['new_price'] = np.where(coffee['Coffee Type'] == 'Espresso', 3.99, 5.99)

In [574]:
coffee['revenue'] = coffee['Units Sold'] * coffee['new_price']

In [376]:
coffee.rename(columns={'new_price': 'price'}, inplace=True)

In [378]:
coffee

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso          25   3.99    99.75
1      Monday       Latte          15   5.99    89.85
2     Tuesday    Espresso          30   3.99   119.70
3     Tuesday       Latte          20   5.99   119.80
4   Wednesday    Espresso          35   3.99   139.65
5   Wednesday       Latte          25   5.99   149.75
6    Thursday    Espresso          40   3.99   159.60
7    Thursday       Latte          30   5.99   179.70
8      Friday    Espresso          45   3.99   179.55
9      Friday       Latte          35   5.99   209.65
10   Saturday    Espresso          45   3.99   179.55
11   Saturday       Latte          35   5.99   209.65
12     Sunday    Espresso          45   3.99   179.55
13     Sunday       Latte          35   5.99   209.65

In [382]:
bios_new = bios.copy()

In [384]:
bios_new['first_name'] = bios_new['name'].str.split(' ').str[0]

In [398]:
bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date'])

In [404]:
bios_new['born_year'] = bios_new['born_datetime'].dt.year
bios_new[['name', 'born_year']].head()

                    name  born_year
0  Jean-François Blanchy     1886.0
1         Arnaud Boetsch     1969.0
2           Jean Borotra     1898.0
3        Jacques Brugnon     1895.0
4           Albert Canet     1878.0

In [414]:
bios_new.to_csv('/Users/mr.tian/Desktop/bios_new.csv', index=False)

In [416]:
bios['height_category'] = bios['height_cm'].apply(lambda x: 'Short' if x < 165 else('Average' if x < 185 else 'Tall'))

In [418]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall

In [444]:
bios.query('born_country == "FRA"').head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN,Average

In [448]:
bios[(bios["height_cm"] > 180) & (bios["weight_kg"] < 70)].head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category
126,127,Claudia Kohde-Kilsch,1963-12-11,Saarbrücken,Saarland,GER,West Germany,184.0,68.0,NaN,Average
298,299,Scott Dumbrell,1961-02-03,NaN,NaN,NaN,Australia,182.0,66.0,NaN,Average
444,445,Markku Syrjälä,1955-05-12,Kurikka,Etelä-Pohjanmaa,FIN,Finland,186.0,65.0,2023-10-11,Tall
585,587,David Pink,1939-12-31,Southend-on-Sea,England,GBR,Great Britain,185.0,68.0,NaN,Tall
924,928,Park Ju-Bong,1964-12-05,NaN,NaN,NaN,Republic of Korea,182.0,68.0,NaN,Average

In [452]:
bios.sort_values(['height_cm', 'weight_kg'], ascending=[False,True]).head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category
89070,89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN,Tall
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN,Tall
6978,7013,Arvydas Sabonis,1964-12-19,Kaunas,Kaunas,LTU,Lithuania Soviet Union,223.0,122.0,NaN,Tall
120266,122147,Zhang Zhaoxu,1987-11-18,Binzhou,Shandong,CHN,People's Republic of China,221.0,110.0,NaN,Tall
5673,5696,Gunther Behnke,1963-01-19,Leverkusen,Nordrhein-Westfalen,GER,Germany,221.0,114.0,NaN,Tall

In [462]:
bios['height_cm'].isna().sum()

38849

In [466]:
bios['weight_kg'].fillna(bios["weight_kg"].mean())

0         71.890996
1         76.000000
2         76.000000
3         64.000000
4         71.890996
            ...
145495    61.000000
145496    65.000000
145497    55.000000
145498    71.890996
145499    71.890996
Name: weight_kg, Length: 145500, dtype: float64

In [470]:
bios['BMI'] = bios.apply(lambda row: row["weight_kg"] / ((row["height_cm"]/100) ** 2), axis=1)

In [472]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,BMI
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,22.694019
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,22.694019
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,22.675737
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,NaN

In [482]:
def categorize_athlete(row):
    if row['height_cm'] < 175 and row['weight_kg'] < 70:
        return 'Lightweight'
    elif row['height_cm'] < 185 or row['weight_kg'] <= 80:
        return 'Middleweight' 
    else:
        return 'Heavyweight'

bios['Category'] = bios.apply(categorize_athlete, axis=1)

In [494]:
bios.drop(columns="height_category").head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,BMI,Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,NaN,Heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,22.694019,Middleweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,22.694019,Middleweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,22.675737,Lightweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,NaN,Heavyweight

In [498]:
nocs = pd.read_csv('/Users/mr.tian/Desktop/noc_regions.csv')

In [502]:
bios_new = pd.merge(bios, nocs, left_on='born_country', right_on='NOC', how='left')

In [510]:
bios_new.rename(columns={'region': 'born_country_full'}, inplace=True)

In [512]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,height_category,BMI,Category,NOC_y,born_country_full,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,NaN,Heavyweight,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,22.694019,Middleweight,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,22.694019,Middleweight,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,22.675737,Lightweight,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,NaN,Heavyweight,GBR,UK,NaN

In [516]:
bios_new[bios_new['NOC_x'] != bios_new['born_country_full']][['name', 'NOC_x', 'born_country_full']]

                       name    NOC_x born_country_full
4              Albert Canet   France                UK
12                J. Defert   France               NaN
13           Étienne Durand   France               NaN
16               Guy Forget   France           Morocco
27       Guy, Baron Lejeune   France               NaN
...                     ...      ...               ...
145491        Matthew Wepke  Jamaica               NaN
145493   Landysh Falyakhova      ROC            Russia
145495    Polina Luchnikova      ROC            Russia
145496  Valeriya Merkusheva      ROC            Russia
145497      Yuliya Smirnova      ROC            Russia

[73210 rows x 3 columns]

In [518]:
usa = bios[bios['born_country'] == 'USA'].copy()
gbr = bios[bios['born_country'] == 'GBR'].copy()

In [524]:
new_df = pd.concat([usa,gbr])

In [532]:
combined_df = pd.merge(results, bios, on='athlete_id', how='left')

In [534]:
combined_df.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,...,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,BMI,Category
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,...,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,NaN,Heavyweight
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,...,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,NaN,Heavyweight
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,...,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,NaN,Heavyweight
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,...,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,NaN,Heavyweight
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,...,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,NaN,Heavyweight

In [536]:
coffee.loc[[0,1], 'Units Sold'] = np.nan

In [550]:
coffee.fillna(coffee['Units Sold'].interpolate())

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso         NaN   3.99    99.75
1      Monday       Latte         NaN   5.99    89.85
2     Tuesday    Espresso        30.0   3.99   119.70
3     Tuesday       Latte        20.0   5.99   119.80
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [552]:
coffee.loc[[2,3], 'Units Sold'] = np.nan

In [554]:
coffee

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso         NaN   3.99    99.75
1      Monday       Latte         NaN   5.99    89.85
2     Tuesday    Espresso         NaN   3.99   119.70
3     Tuesday       Latte         NaN   5.99   119.80
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [556]:
coffee[coffee['Units Sold'].isna()]

       Day Coffee Type  Units Sold  price  revenue
0   Monday    Espresso         NaN   3.99    99.75
1   Monday       Latte         NaN   5.99    89.85
2  Tuesday    Espresso         NaN   3.99   119.70
3  Tuesday       Latte         NaN   5.99   119.80

In [582]:
coffee.rename(columns={'new_price': 'price'}, inplace=True)

In [594]:
coffee.groupby(['Coffee Type', 'Day']).agg({'Units Sold': 'sum', 'price':'mean'})

                       Units Sold  price
Coffee Type Day
Espresso    Friday             45   3.99
            Monday             25   3.99
            Saturday           45   3.99
            Sunday             45   3.99
            Thursday           40   3.99
            Tuesday            30   3.99
            Wednesday          35   3.99
Latte       Friday             35   5.99
            Monday             15   5.99
            Saturday           35   5.99
            Sunday             35   5.99
            Thursday           30   5.99
            Tuesday            20   5.99
            Wednesday          25   5.99

In [596]:
pivot = coffee.pivot(columns='Coffee Type', index='Day', values='revenue')

In [602]:
pivot.sum(axis=1)

Day
Friday       389.2
Monday       189.6
Saturday     389.2
Sunday       389.2
Thursday     339.3
Tuesday      239.5
Wednesday    289.4
dtype: float64

In [614]:
bios['born_date'] = pd.to_datetime(bios['born_date'])
bios.groupby(bios['born_date'].dt.year)['name'].count().reset_index().sort_values('name', ascending=False)

     born_date  name
139     1972.0  2231
152     1985.0  2227
140     1973.0  2216
138     1971.0  2205
137     1970.0  2174
..         ...   ...
2       1833.0     1
10      1843.0     1
6       1839.0     1
12      1845.0     1
176     2009.0     1

[177 rows x 2 columns]

In [626]:
latte = coffee[coffee['Coffee Type'] == 'Latte'].copy()

In [628]:
latte['3Day'] = latte['Units Sold'].rolling(3).sum()

In [630]:
latte

          Day Coffee Type  Units Sold  price  revenue   3Day
1      Monday       Latte          15   5.99    89.85    NaN
3     Tuesday       Latte          20   5.99   119.80    NaN
5   Wednesday       Latte          25   5.99   149.75   60.0
7    Thursday       Latte          30   5.99   179.70   75.0
9      Friday       Latte          35   5.99   209.65   90.0
11   Saturday       Latte          35   5.99   209.65  100.0
13     Sunday       Latte          35   5.99   209.65  105.0

In [632]:
pd.__version__

'2.2.2'